image: node:latest

pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install
  stage: deploy
  script:
  - rm -rdf public
  - npm run firebase
  artifacts:
    paths:
    - public
  only:
    - dev
