image: node:latest

pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install
  stage: deploy
  script:
  - npm run ghpages
  - git checkout -b gh-pages
  artifacts:
    paths:
    - docs
  only:
    - dev
