language: 
branches:
  only:
    - master
before_script: 
  - git config --global user.email "stefano.antonel@epfl.ch"
  - git config --global user.name "Stefano Antonel"
  - git remote rm origin
  - https://antonelepfl:${b2a2a54f7cc922244ef6442e7163d4a27c615ba6}@github.com/antonelepfl/usecases.git
node_js: "6""
install: npm install
script: 
  - npm run ghpages
  - gem install travis
  - travis encrypt GH_TOKEN="b2a2a54f7cc922244ef6442e7163d4a27c615ba6" --add
  - git add .
  - git commit -m "Deploy"
env:
  global:
    secure: "encrypted-github-token"