language: node_js
node_js: "node"
branches:
  only:
    - master
before_script: 
  - git config --global user.email "stefano.antonel@epfl.ch"
  - git config --global user.name "Stefano Antonel"
  - git remote rm origin 
  - git remote add origin https://antonelepfl:${GH_TOKEN}@github.com/antonelepfl/usecases.git
install: npm install
script: 
  - npm run ghpages
  - git add --all
  - git commit -m "Deploy"
  - git push origin gh-pages