language: node_js
node_js: "node"
branches:
  only:
    - master
before_script: 
  - git config --global user.email "stefano.antonel@epfl.ch"
  - git config --global user.name "antonelepfl"
  - git remote rm origin 
  - git remote add origin https://${GH_TOKEN}@github.com/antonelepfl/usecases.git
install: 
  - npm install
  - gem install travis
script: 
  - travis encrypt ${GH_TOKEN} --add
  - npm run ghpages
  - git checkout -b gh-pages
  - cp -R ./docs/* ./ && rm -R docs/
  - git add --all 
  - git commit -m "Deploy"
  - git push origin gh-pages
env:
  global:
    secure: ${GH_PUBLIC_KEY}