language: node_js
node_js: "node"
branches:
  only:
    - master
before_script: 
  - git config --global user.email "stefano.antonel@epfl.ch"
  - git config --global user.name "Stefano Antonel"
  - git remote rm origin 
  - git remote add origin https://antonelepfl:ad5afbb57f187aedb337a4f60ca412cb8e2ce2ac@github.com/antonelepfl/usecases.git
install: npm install
script: 
  - gem install travis
  - travis encrypt GH_TOKEN="ad5afbb57f187aedb337a4f60ca412cb8e2ce2ac" --add --skip-completion-check
  - y
  - npm run ghpages
  - git checkout gh-pages
  - cp -R ./docs/* ./ && rm -R docs/
  - git add --all 
  - git commit -m "Deploy"
  - git push origin gh-pages
env:
  global:
    secure: GH-TOKEN